# Generated by Django 4.2 on 2023-11-17 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default=1, max_length=2)),
                ('price', models.FloatField(default=0, max_length=(15, 2))),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fuel type list',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0, max_length=(15, 2))),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='management.fuel')),
            ],
            options={
                'verbose_name_plural': 'Stock-In Records',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0, max_length=(15, 2))),
                ('date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0, max_length=(15, 2))),
                ('amount', models.FloatField(default=0, max_length=(15, 2))),
                ('date_sold', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='management.fuel')),
            ],
            options={
                'verbose_name_plural': 'List of Sales',
            },
        ),
    ]
